SHREK Job Submission 2022-08-19 13:01:25.037806
shrek/scripts/submitWorflowToPanDA.py --no-uuid --tag sP22r-hfcharm-pileup-cond1 workflows/HF_pp200_charm-ana.315-conditional/runPileup.yaml workflows/HF_pp200_charm-ana.315-conditional/runCalorimeter.yaml workflows/HF_pp200_charm-ana.315-conditional/runPass3Track.yaml workflows/HF_pp200_charm-ana.315-conditional/runPass4TrackStage0.yaml workflows/HF_pp200_charm-ana.315-conditional/runPass4TrackStageA.yaml workflows/HF_pp200_charm-ana.315-conditional/runPass4TrackStageC.yaml workflows/HF_pp200_charm-ana.315-conditional/mergeOutputs.yaml --submit
cmd args: 
Namespace(yaml=['workflows/HF_pp200_charm-ana.315-conditional/runPileup.yaml', 'workflows/HF_pp200_charm-ana.315-conditional/runCalorimeter.yaml', 'workflows/HF_pp200_charm-ana.315-conditional/runPass3Track.yaml', 'workflows/HF_pp200_charm-ana.315-conditional/runPass4TrackStage0.yaml', 'workflows/HF_pp200_charm-ana.315-conditional/runPass4TrackStageA.yaml', 'workflows/HF_pp200_charm-ana.315-conditional/runPass4TrackStageC.yaml', 'workflows/HF_pp200_charm-ana.315-conditional/mergeOutputs.yaml'], tag='sP22r-hfcharm-pileup-cond1', offset=0, submit=True, check=True, handshake=True, uuid=False, vo='wlcg', site='BNL_OSG_SPHENIX', prodSourceLabel='test', workingGroup='sphenix', user='jwebb2', branch='test')
subdir: 
/direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22r-hfcharm-pileup-cond1
tag: 
sP22r-hfcharm-pileup-cond1
check:
b'INFO : uploading workflow sandbox\nINFO : check workflow user.jwebb2.sP22r-hfcharm-pileup-cond1\nINFO : messages from the server\n2022-08-19 17:01:23.980902 : start /var/cache/pandaserver/workflow.738fd2ad-88c7-47b9-8aa7-58bfe6413799\n2022-08-19 17:01:24.477535 : downloading sandbox from https://pandaserver-doma.cern.ch:25443/cache/jobO.5679ad9c-a0c5-4473-9511-2d44d341876e.tar.gz\n2022-08-19 17:01:24.515745 : parse workflow\n2022-08-19 17:01:24.856767 : failed to run with - tried _RecordLoader but\n  Not a CommandLineTool\n- tried _RecordLoader but\n  Not a ExpressionTool\n- tried _RecordLoader but\n  Trying \'Workflow\'\nsP22r-hfcharm-pileup-cond1-workflow.cwl:19:1:     the `steps` field is not valid because:\n                                                    tried _ArrayLoader but\n                                                      - tried _ArrayLoader but\n                                                        Expected a list\n                                                      - tried _RecordLoader but\n                                                        Trying \'WorkflowStep\'\nsP22r-hfcharm-pileup-cond1-workflow.cwl:70:5:             invalid field `when`, expected one of:\n                                                          `id`, `in`, `out`, `requirements`, `hints`, `label`,\n                                                          `doc`, `run`, `scatter`, `scatterMethod`\n- tried _ArrayLoader but\n  Expected a list Traceback (most recent call last):\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/workflow_processor.py", line 169, in core_exec\n    tmpLog)\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/workflow/pcwl_utils.py", line 56, in parse_workflow_file\n    root_obj = load_document_by_uri(cwl_file)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 80, in load_document_by_uri\n    return load_document_by_string(doc, baseuri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 102, in load_document_by_string\n    return load_document_by_yaml(result, uri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 112, in load_document_by_yaml\n    yaml, uri, cast(Optional[cwl_v1_0.LoadingOptions], loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 12267, in load_document_by_yaml\n    loadingOptions,\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 580, in _document_load\n    return loader.load(doc, baseuri, loadingOptions, docRoot=baseuri)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 417, in load\n    raise ValidationException("", None, errors, "-")\nschema_salad.exceptions.ValidationException: - tried _RecordLoader but\n  Not a CommandLineTool\n- tried _RecordLoader but\n  Not a ExpressionTool\n- tried _RecordLoader but\n  Trying \'Workflow\'\nsP22r-hfcharm-pileup-cond1-workflow.cwl:19:1:     the `steps` field is not valid because:\n                                                    tried _ArrayLoader but\n                                                      - tried _ArrayLoader but\n                                                        Expected a list\n                                                      - tried _RecordLoader but\n                                                        Trying \'WorkflowStep\'\nsP22r-hfcharm-pileup-cond1-workflow.cwl:70:5:             invalid field `when`, expected one of:\n                                                          `id`, `in`, `out`, `requirements`, `hints`, `label`,\n                                                          `doc`, `run`, `scatter`, `scatterMethod`\n- tried _ArrayLoader but\n  Expected a list\n\n\nERROR : workflow description is corrupted\n'
b''
submit:
2022-08-19 17:01:29.349468
b'INFO : uploading workflow sandbox\nINFO : gathering files under /direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22r-hfcharm-pileup-cond1\nINFO : upload source files\nINFO : submit workflow user.jwebb2.sP22r-hfcharm-pileup-cond1\nINFO : request was accepted and will be processed in a few minutes\n'
b''