SHREK Job Submission 2022-08-04 11:42:01.282242
cmd args: 
Namespace(yaml=['workflows/HF_pp200_threestep/runCharmSimuFinish.yaml', 'workflows/HF_pp200_threestep/runCharmSimu.yaml'], tag='sP22n-hfcharm-signal', offset=100000, submit=True, check=True, handshake=True, uuid=False, vo='wlcg', site='BNL_OSG_SPHENIX', prodSourceLabel='test', workingGroup='sphenix', user='jwebb2', branch='test')
subdir: 
/direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22n-hfcharm-signal
tag: 
sP22n-hfcharm-signal
check:
b'INFO : uploading workflow sandbox\nINFO : check workflow user.jwebb2.sP22n-hfcharm-signal\nINFO : messages from the server\n2022-08-04 15:42:00.202457 : start /var/cache/pandaserver/workflow.677efee1-a1ba-4b84-9d85-9f507e030d0c\n2022-08-04 15:42:00.777928 : downloading sandbox from https://pandaserver-doma.cern.ch:25443/cache/jobO.20571d1e-6951-4fa6-b927-6d2cc365fe5e.tar.gz\n2022-08-04 15:42:00.817885 : parse workflow\n2022-08-04 15:42:01.109495 : failed to run with - tried _RecordLoader but\n  Not a CommandLineTool\n- tried _RecordLoader but\n  Not a ExpressionTool\n- tried _RecordLoader but\n  Trying \'Workflow\'\nsP22n-hfcharm-signal-workflow.cwl:9:1:     the `steps` field is not valid because:\n                                             tried _ArrayLoader but\n                                               Expected a list\n- tried _ArrayLoader but\n  Expected a list Traceback (most recent call last):\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/workflow_processor.py", line 169, in core_exec\n    tmpLog)\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/workflow/pcwl_utils.py", line 56, in parse_workflow_file\n    root_obj = load_document_by_uri(cwl_file)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 80, in load_document_by_uri\n    return load_document_by_string(doc, baseuri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 102, in load_document_by_string\n    return load_document_by_yaml(result, uri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 112, in load_document_by_yaml\n    yaml, uri, cast(Optional[cwl_v1_0.LoadingOptions], loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 12267, in load_document_by_yaml\n    loadingOptions,\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 580, in _document_load\n    return loader.load(doc, baseuri, loadingOptions, docRoot=baseuri)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 417, in load\n    raise ValidationException("", None, errors, "-")\nschema_salad.exceptions.ValidationException: - tried _RecordLoader but\n  Not a CommandLineTool\n- tried _RecordLoader but\n  Not a ExpressionTool\n- tried _RecordLoader but\n  Trying \'Workflow\'\nsP22n-hfcharm-signal-workflow.cwl:9:1:     the `steps` field is not valid because:\n                                             tried _ArrayLoader but\n                                               Expected a list\n- tried _ArrayLoader but\n  Expected a list\n\n\nERROR : workflow description is corrupted\n'
b''
submit:
2022-08-04 15:42:05.156940
b'INFO : uploading workflow sandbox\nINFO : gathering files under /direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22n-hfcharm-signal\nINFO : upload source files\nINFO : submit workflow user.jwebb2.sP22n-hfcharm-signal\nINFO : request was accepted and will be processed in a few minutes\n'
b''