SHREK Job Submission 2022-08-11 20:22:00.516500
cmd args: 
Namespace(yaml=['workflows/HF_pp200_charm-ana.315/runCharmSimu.yaml'], tag='sP22r-hfcharm-signal-test3', offset=200000, submit=True, check=True, handshake=True, uuid=False, vo='wlcg', site='BNL_OSG_SPHENIX', prodSourceLabel='test', workingGroup='sphenix', user='jwebb2', branch='test')
subdir: 
/direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22r-hfcharm-signal-test3
tag: 
sP22r-hfcharm-signal-test3
check:
b'INFO : uploading workflow sandbox\nINFO : check workflow user.jwebb2.sP22r-hfcharm-signal-test3\nINFO : messages from the server\n2022-08-12 00:21:59.507697 : start /var/cache/pandaserver/workflow.aa63dcad-193c-4553-880e-bb71e2c325cc\n2022-08-12 00:21:59.997887 : downloading sandbox from https://pandaserver-doma.cern.ch:25443/cache/jobO.8cb6cc99-2546-48fc-a9d3-a752df5a57b7.tar.gz\n2022-08-12 00:22:00.040680 : parse workflow\n2022-08-12 00:22:00.341780 : failed to run with - tried _RecordLoader but\n  Not a CommandLineTool\n- tried _RecordLoader but\n  Not a ExpressionTool\n- tried _RecordLoader but\n  Trying \'Workflow\'\nsP22r-hfcharm-signal-test3-workflow.cwl:9:1:     the `steps` field is not valid because:\n                                                   tried _ArrayLoader but\n                                                     Expected a list\n- tried _ArrayLoader but\n  Expected a list Traceback (most recent call last):\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/workflow_processor.py", line 169, in core_exec\n    tmpLog)\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/workflow/pcwl_utils.py", line 56, in parse_workflow_file\n    root_obj = load_document_by_uri(cwl_file)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 80, in load_document_by_uri\n    return load_document_by_string(doc, baseuri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 102, in load_document_by_string\n    return load_document_by_yaml(result, uri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 112, in load_document_by_yaml\n    yaml, uri, cast(Optional[cwl_v1_0.LoadingOptions], loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 12267, in load_document_by_yaml\n    loadingOptions,\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 580, in _document_load\n    return loader.load(doc, baseuri, loadingOptions, docRoot=baseuri)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/cwl_v1_0.py", line 417, in load\n    raise ValidationException("", None, errors, "-")\nschema_salad.exceptions.ValidationException: - tried _RecordLoader but\n  Not a CommandLineTool\n- tried _RecordLoader but\n  Not a ExpressionTool\n- tried _RecordLoader but\n  Trying \'Workflow\'\nsP22r-hfcharm-signal-test3-workflow.cwl:9:1:     the `steps` field is not valid because:\n                                                   tried _ArrayLoader but\n                                                     Expected a list\n- tried _ArrayLoader but\n  Expected a list\n\n\nERROR : workflow description is corrupted\n'
b''
submit:
2022-08-12 00:22:04.230678
b'INFO : uploading workflow sandbox\nINFO : gathering files under /direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22r-hfcharm-signal-test3\nINFO : upload source files\nINFO : submit workflow user.jwebb2.sP22r-hfcharm-signal-test3\nINFO : request was accepted and will be processed in a few minutes\n'
b''